name: Deploy Prod

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build + Push Backend
        run: |
          docker build \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/software-backend:latest \
            -f software/Dockerfile.prod \
            software-backend

          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/software-backend:latest

      - name: Build + Push Frontend
        run: |
          docker build \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/software-frontend:latest \
            --build-arg VITE_API_URL=/api \
            -f frontend/Dockerfile.prod \
            frontend

          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/software-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/ubuntu/crm

            docker-compose -f docker-compose.prod.yml down

            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/software-backend:latest
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/software-frontend:latest

            docker-compose -f docker-compose.prod.yml up -d --force-recreate --no-build
